workspace(name = "helloworld")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "jsoncpp",
  build_file = "//third_party:jsoncpp.BUILD",
  sha256 = "c49deac9e0933bcb7044f08516861a2d560988540b23de2ac1ad443b219afdb6",
  strip_prefix = "jsoncpp-1.8.4",
  urls = [
    "https://github.com/open-source-parsers/jsoncpp/archive/1.8.4.tar.gz",
  ],
)

http_archive(
  name = "libpng",
  build_file = "//third_party:libpng.BUILD",
  sha256 = "e45ce5f68b1d80e2cb9a2b601605b374bdf51e1798ef1c2c2bd62131dfcf9eef",
  strip_prefix = "libpng-1.6.34",
  urls = [
    "https://mirror.bazel.build/github.com/glennrp/libpng/archive/v1.6.34.tar.gz",
    "https://github.com/glennrp/libpng/archive/v1.6.34.tar.gz",
  ],
)

http_archive(
  name = "zlib",
  build_file = "//third_party:zlib.BUILD",
  sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
  strip_prefix = "zlib-1.2.11",
  urls = [
    "https://mirror.bazel.build/zlib.net/zlib-1.2.11.tar.gz",
    "https://zlib.net/zlib-1.2.11.tar.gz",
  ],
)