workspace(name = "helloworld")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "jsoncpp",
  build_file = "//third_party:jsoncpp.BUILD",
  sha256 = "c49deac9e0933bcb7044f08516861a2d560988540b23de2ac1ad443b219afdb6",
  strip_prefix = "jsoncpp-1.8.4",
  urls = [
    "https://github.com/open-source-parsers/jsoncpp/archive/1.8.4.tar.gz",
  ],
)
    