package(default_visibility = ["//visibility:public"])

cc_library(
    name = "helpers",
    srcs = [
      "io.cc"
    ],
    hdrs = [
      "image.h",
      "io.h"
    ],
    deps = [
        "@png_archive//:png"
    ]
)
